version: "3.8"

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    container_name: financedb
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: financedb
    
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
